/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/*
 *	Filename	= Menu.java
 *	Author		= Azzahra Siti Hadjar
 *	NIM		= 2100901 
 *      Email           = azzahrasth@upi.edu
 *	Deskripsi 	= view untuk menampilkan menu game (data user)
 */

package view;

// import library
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.Clip;
import javax.swing.JOptionPane;

// akses package viewmodel
import viewmodel.Game;
import viewmodel.Sound;
import viewmodel.TableProcess;

/**
 *
 * @author sitih
 */
public class Menu extends javax.swing.JFrame {
    // atribut
    public Game game; // objek game
    private TableProcess tableScore; // data tabel tscore pada database
    public Clip musik; // backsound game
    private String username; // username
    
    public Menu() {
        // konstruktor
        initComponents(); // meload component
        this.username = ""; // inisialisasi username
        try {
            // membuat tabel proses tscore
            this.tableScore = new TableProcess();
            // mengambil data tscore dari database untuk isian tabel pada frame menu
            TableScore.setModel(tableScore.setTable());
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        
        // play musik untuk menu game
        musik  = new Sound().playSound(this.musik, "1_Game_Menu.wav");
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        buttonPlay = new javax.swing.JButton();
        labelJudul = new javax.swing.JLabel();
        buttonQuit = new javax.swing.JButton();
        jScrollPane = new javax.swing.JScrollPane();
        TableScore = new javax.swing.JTable();
        labelUsername = new javax.swing.JLabel();
        TextFieldUsername = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Keep Standing - TMD DPBO 2023");

        jPanel.setBackground(new java.awt.Color(0, 153, 153));
        jPanel.setForeground(new java.awt.Color(153, 255, 255));

        buttonPlay.setBackground(new java.awt.Color(51, 255, 102));
        buttonPlay.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        buttonPlay.setForeground(new java.awt.Color(255, 255, 255));
        buttonPlay.setText("Play");
        buttonPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPlayActionPerformed(evt);
            }
        });

        labelJudul.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 36)); // NOI18N
        labelJudul.setForeground(new java.awt.Color(51, 0, 0));
        labelJudul.setText("KEEP STANDING");
        labelJudul.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        labelJudul.setAlignmentY(0.0F);
        labelJudul.setIconTextGap(0);

        buttonQuit.setBackground(new java.awt.Color(255, 102, 102));
        buttonQuit.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        buttonQuit.setForeground(new java.awt.Color(255, 255, 255));
        buttonQuit.setText("Quit");
        buttonQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonQuitActionPerformed(evt);
            }
        });

        TableScore.setBackground(new java.awt.Color(204, 255, 255));
        TableScore.setForeground(new java.awt.Color(51, 0, 0));
        TableScore.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        TableScore.setGridColor(new java.awt.Color(0, 51, 51));
        TableScore.setName(""); // NOI18N
        TableScore.setPreferredSize(new java.awt.Dimension(225, 200));
        TableScore.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableScoreMouseClicked(evt);
            }
        });
        jScrollPane.setViewportView(TableScore);

        labelUsername.setBackground(new java.awt.Color(0, 51, 51));
        labelUsername.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        labelUsername.setForeground(new java.awt.Color(255, 255, 255));
        labelUsername.setText("Username : ");

        TextFieldUsername.setBackground(new java.awt.Color(204, 255, 255));
        TextFieldUsername.setForeground(new java.awt.Color(51, 0, 0));
        TextFieldUsername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextFieldUsername.setToolTipText("Username...");
        TextFieldUsername.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TextFieldUsername.setCaretColor(new java.awt.Color(0, 102, 102));
        TextFieldUsername.setSelectedTextColor(new java.awt.Color(0, 102, 102));
        TextFieldUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldUsernameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(buttonPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonQuit, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                        .addComponent(labelUsername)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                        .addComponent(labelJudul)
                        .addGap(78, 78, 78))))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(labelJudul)
                .addGap(30, 30, 30)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUsername)
                    .addComponent(TextFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonQuit, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 416, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPlayActionPerformed
        // TODO add your handling code here:
       
        if( TextFieldUsername.getText().length() != 0 ) 
        {// jika textfield ada isi 
            
            // simpan isi text field ke dalam username
            this.username = TextFieldUsername.getText(); 
        }
        
        if(this.username.length() == 0) 
        {// jika nilai username masih kosong 
            
            JOptionPane.showMessageDialog(this, "Masukkan username baru atau pilih user yang ada pada tabel!");
        }
        else 
        {
            // stop musik window menu
           new Sound().stopSound(this.musik);

            // buat game baru
            game = new Game(this.username);
            GameWindow gw = new GameWindow(game); // buat window game

            // memulai game
            game.StartGame(gw);
            this.setVisible(false);  // set frame menu menjadi invisible
            this.dispose(); // frame menu di clear
        }
    }//GEN-LAST:event_buttonPlayActionPerformed

    private void buttonQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonQuitActionPerformed
        // TODO add your handling code here:
        this.dispose(); // frame menu di clear
        System.exit(0);
    }//GEN-LAST:event_buttonQuitActionPerformed

    private void TableScoreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableScoreMouseClicked
        // TODO add your handling code here:
        // jika salah satu data dalam tabel di klik
        int row = TableScore.getSelectedRow();
        // set username dengan username pada data yg di klik
        this.username = TableScore.getModel().getValueAt(row, 0).toString();
    }//GEN-LAST:event_TableScoreMouseClicked

    private void TextFieldUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldUsernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableScore;
    private javax.swing.JTextField TextFieldUsername;
    private javax.swing.JButton buttonPlay;
    private javax.swing.JButton buttonQuit;
    private javax.swing.JPanel jPanel;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JLabel labelJudul;
    private javax.swing.JLabel labelUsername;
    // End of variables declaration//GEN-END:variables
}
